### PR TITLE
minor edit: fix the reference table formatting

### PR DESCRIPTION
**Pull request by j23414**
Thanks for putting this together! Just wanted to fix the formatting in the README table.

### CODE REVIEW

**Comment by arendsee** [comment]
Thanks @j23414 ! Looks good!

**Comment by j23414** [comment]
Ah, might need to contact @markin-alex or @tkanderson to merge.

**Comment by tkanderson** [comment]
Thanks @j23414 and @arendsee

**Comment by j23414** [comment]
Looks like it's hitting a [TypeCheck problem](https://github.com/flu-crew/flutile/actions/runs/4056720653/jobs/6981560567):

```
Run mypy --python-version 3.10 flutile/*py
flutile/api.py:30: error: Incompatible types in assignment (expression has type "TextIO", variable has type "TextIOWrapper")  [assignment]
flutile/api.py:35: error: Incompatible types in assignment (expression has type "TextIO", variable has type "TextIOWrapper")  [assignment]
Found 2 errors in 1 file (checked [7](https://github.com/flu-crew/flutile/actions/runs/4056720653/jobs/6981560567#step:6:8) source files)
Error: Process completed with exit code 1.
```

Which happens in app.py (not triggered by changes from this PR): 

https://github.com/flu-crew/flutile/blob/e5b343fa0203e4d8119cad24b42b6e722d9a0be2/flutile/api.py#L27-L35

And seems related to:

* https://stackoverflow.com/questions/43910979/mypy-error-incompatible-types-in-assignment

Which means we need to explicitly define `fasta_fh` and `outfile_fh` as either type `TextIO` or `TextIOWrapper`? Assuming they auto convert to each other?

**Comment by tkanderson** [comment]
@btski when you get back to work, can you see if this will cause issues in the downstream/octofludb?

@j23414 thanks - I noticed the error :-) but then got swept into other things and didn't look further.

> Which means we need to explicitly define `fasta_fh` and `outfile_fh` as either type `TextIO` or `TextIOWrapper`? Assuming they auto convert to each other?

**Comment by arendsee** [comment]
Or you could just disable the typechecking step in the git actions file. That's how I fix failing tests.

**Comment by tkanderson** [comment]
Apparently rerunning the job reuses the original yaml file? I'll give it another go later today (deleted the typechecking) - getting a crash course in git beyond my regular old commit/push/pull stuff...

**Pull request merged**
